### ISSUE TITLE
Lora Download: Wrong directory

### ISSUE THREAD

**Issue by elBlacksmith** [camenduru/sd-civitai-browser#13]
Hi,

I was triying to download a LORA but it didn´t appear on my list, even if I refresehd the folder.
Taking a look to the log, I saw they are being downloaded to "/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora" instead of "/stable-diffusion-webui/models/Lora"

**Comment by camenduru** [comment]
Hi @elBlacksmith 👋 please uncheck the `save LoRA to additional-networks`

**Comment by elBlacksmith** [comment]
@camenduru Ok. It works,
Thanks.

It´s a bit weird, I don´t think I used that option.
