### ISSUE TITLE
The extension is not searching anything

### ISSUE THREAD

**Issue by DevilSinister** [camenduru/sd-civitai-browser#19]
The extension doesn't seem to work at all in google colab. I am typing terms to search and its not even pulling the list. the get list button does nothing. I have tried to get loras, embedding but same results. I even tried with search nsfw on and off and by searching with term and without term but its not getting anything. Any Ideas what the issue might be??

**Comment by camenduru** [comment]
please try https://github.com/Vetchems/sd-civitai-browser
