### ISSUE TITLE
help?? use it lora error

### ISSUE THREAD

**Issue by fromymrm** [camenduru/sd-civitai-browser#9]
![error](https://user-images.githubusercontent.com/125830422/219973716-0b751471-9c52-4691-b823-c563612421fd.png), 
when i use lora after downloading it he give this error

extensions/sd-webui-additional-networks/models/lora/CZ2128_Shizu_Delta_Overlord/cz2128ShizuDelta_v10.safetensors successfully downloaded.
LoRA weight: 1, model: cz2128ShizuDelta_v10(c5aa8aa0)
Error running process: /content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 338, in process
    script.process(p, *script_args)
  File "/content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 177, in process
    network, info = lora_compvis.create_network_and_apply_compvis(du_state_dict, weight, text_encoder, unet)
  File "/content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/lora_compvis.py", line 73, in create_network_and_apply_compvis
    network_dim = min([s for s in size if s > 1])
ValueError: min() arg is an empty sequence

Same problem happened to me with many (lora)

**Comment by camenduru** [comment]
Hi @fromymrm 👋 please try `v2.1` 

find this line 
`!git clone -b v2.0 https://github.com/camenduru/stable-diffusion-webui `

change to this 
`!git clone -b v2.1 https://github.com/camenduru/stable-diffusion-webui `

and please tell me if it worked

**Comment by fromymrm** [comment]
hi @camenduru 

All versions here are 1.6
should I change them all to to 2.1

![Capture](https://user-images.githubusercontent.com/125830422/220152290-4f1e0665-887c-419f-a94c-b95bcfaf49a7.PNG)

**Comment by fromymrm** [comment]
I tried to change it like you told me in anything_3_webui_colab.ipynb

![1](https://user-images.githubusercontent.com/125830422/220156655-0a2e7303-69c3-4e9d-8dfb-d09194c13db4.PNG)

but he give me this error 

![2](https://user-images.githubusercontent.com/125830422/220156752-8fb82d77-469f-4329-b1af-94b2608bc0aa.PNG)

and i change same line on stable_diffusion_v2_1_webui_colab.ipynb

give me and give Another error :(

![3](https://user-images.githubusercontent.com/125830422/220159111-a5faa314-a7e1-49b2-aaac-ca6f1e22df64.PNG)

**Comment by camenduru** [comment]
True, sorry. I think we solved it. Can you please give me the LoRA link?

**Comment by fromymrm** [comment]
No problem, my friend, that you are doing a good job, and you have all thanks and appreciation for your efforts. The program works in an excellent way

this link of one of them
https://civitai.com/models/10229/march-7th-or-honkai-star-rail

I have some notes
First, checkpoint It works well, but Hypernetwork is having a problem with it. I don't know how to run it after downloading it. There is no place for me to run it like lora

secondly, if this https://www.youtube.com/@camenduru/featured is your channel on YouTube, it is very good and useful, keep downloading the videos, and the community will definitely support you

Thank you for your quick reply and your excellent work and you have all my appreciation.

**Comment by camenduru** [comment]
Lora looks like working
![image (2)](https://user-images.githubusercontent.com/54370274/220178326-86af75fd-b05a-4ced-bd1a-aabde28413cc.png)
![image (3)](https://user-images.githubusercontent.com/54370274/220178341-b750fc8d-bf94-474f-a963-5b2b3388d05c.png)

and for hypernetwork please use this button 

![Screenshot_2023-02-20_202159](https://user-images.githubusercontent.com/54370274/220178548-6fb7167a-5517-4e42-bf0b-6a6b400b75a3.jpg)

 yep my channel thanks ❤

**Comment by fromymrm** [comment]
wow nice work
 but what stable diffusion webui colab i i should use

**Comment by fromymrm** [comment]
I tried now and same error :(

![1](https://user-images.githubusercontent.com/125830422/220181516-58019240-53ba-433d-a1de-31951a5cd3d8.PNG)
![2](https://user-images.githubusercontent.com/125830422/220181526-16baf044-0915-4259-9d8a-bc5a8f244a33.PNG)
![3](https://user-images.githubusercontent.com/125830422/220181538-561cc5b5-9c53-4f1a-a33a-6f9e5d7d1c9b.PNG)

**Comment by fromymrm** [comment]
i don't have the same option in  stable diffusion webui


![4](https://user-images.githubusercontent.com/125830422/220182384-099a1f58-4054-4072-bab1-580306a34635.PNG)

**Comment by camenduru** [comment]
please try this https://github.com/camenduru/stable-diffusion-webui-colab/tree/v2.0

**Comment by fromymrm** [comment]
Yes, yes, it worked for me now
Thank you very much for helping me.
 I wish you more success <3
